import java.util.List;
import java.util.ArrayList;
import java.util.Scanner;

public class Main{
    public static void class main(String[] args){
    Scanner scan = new Scanner(system.is);
    int opcion = 0;
    do{
    switch (opcion)
    opcion = system.out.println(scan.nextline)
    System.out.println("1. Registrar Material");
    System.out.println("2. Listar Catalogo");
    System.out.println("3. Prestar Material");
    System.out.println("4. Resumen del catalogo");
    System.out.println("6. Salir");
    System.out.println("Seleccione una opcion")
    case 1:
        
    }
    }
}